CREATE TABLE activity_types (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  label TEXT NOT NULL,
  emoji TEXT,
  icon_url TEXT,
  category TEXT CHECK (category IN ('mountain','water','snow','air','nature')),
  is_seasonal BOOLEAN DEFAULT false,
  seasons TEXT[] DEFAULT '{}',
  sort_order INTEGER DEFAULT 0
);

INSERT INTO activity_types (slug, label, emoji, category, seasons, sort_order) VALUES
  ('mtb', 'Mountain Biking', '🚵', 'mountain', '{spring,summer,fall}', 1),
  ('hiking', 'Hiking', '🥾', 'mountain', '{spring,summer,fall}', 2),
  ('trail_running', 'Trail Running', '🏃', 'mountain', '{spring,summer,fall}', 3),
  ('climbing', 'Rock Climbing', '🧗', 'mountain', '{spring,summer,fall}', 4),
  ('road_cycling', 'Road Cycling', '🚴', 'mountain', '{spring,summer,fall}', 5),
  ('camping', 'Camping', '🏕️', 'mountain', '{spring,summer,fall}', 6),
  ('horseback', 'Horseback Riding', '🏇', 'mountain', '{spring,summer,fall}', 7),
  ('disc_golf', 'Disc Golf', '🥏', 'mountain', '{spring,summer,fall}', 8),
  ('orienteering', 'Orienteering', '🧭', 'mountain', '{spring,summer,fall}', 9),
  ('fly_fishing', 'Fly Fishing', '🎣', 'mountain', '{spring,summer,fall}', 10),
  ('kayaking', 'Kayaking / Paddling', '🛶', 'water', '{spring,summer,fall}', 11),
  ('surfing', 'Surfing', '🏄', 'water', '{all}', 12),
  ('scuba', 'Scuba / Snorkeling', '🤿', 'water', '{summer,fall}', 13),
  ('kitesurfing', 'Kite Surfing', '🪁', 'water', '{spring,summer,fall}', 14),
  ('wild_swimming', 'Wild Swimming', '🏊', 'water', '{summer}', 15),
  ('motorized_water', 'Motorized Water Sports', '🚤', 'water', '{summer}', 16),
  ('standup_paddle', 'Stand-Up Paddleboard', '🏄', 'water', '{spring,summer,fall}', 17),
  ('whitewater', 'Whitewater Rafting', '🌊', 'water', '{spring,summer}', 18),
  ('skiing', 'Skiing', '⛷️', 'snow', '{winter}', 19),
  ('snowboarding', 'Snowboarding', '🏂', 'snow', '{winter}', 20),
  ('nordic_skiing', 'Nordic Skiing', '🎿', 'snow', '{winter}', 21),
  ('snowshoeing', 'Snowshoeing', '🥾', 'snow', '{winter}', 22),
  ('ice_climbing', 'Ice Climbing', '🧊', 'snow', '{winter}', 23),
  ('paragliding', 'Paragliding', '🪂', 'air', '{spring,summer,fall}', 24),
  ('drone_flying', 'Drone Flying', '🛸', 'air', '{all}', 25),
  ('wildlife_photography', 'Wildlife Photography', '📸', 'nature', '{all}', 26),
  ('birdwatching', 'Birdwatching', '🦅', 'nature', '{all}', 27),
  ('outdoor_yoga', 'Outdoor Yoga', '🧘', 'nature', '{spring,summer,fall}', 28),
  ('foraging', 'Foraging', '🍄', 'nature', '{spring,summer,fall}', 29);
