// Types are defined inline to avoid external dependency issues in preview mode

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const now = new Date();
const daysFromNow = (d: number) =>
  new Date(now.getTime() + d * 86400000).toISOString();
const daysAgo = (d: number) =>
  new Date(now.getTime() - d * 86400000).toISOString();

// ---------------------------------------------------------------------------
// Regions (for Trip Planner)
// ---------------------------------------------------------------------------

export interface MockRegion {
  slug: string;
  name: string;
  state_province: string;
  country: string;
  continent: string;
  description: string;
  coverEmoji: string;
  trailCount: number;
  businessCount: number;
  hasData: boolean;
}

export const MOCK_REGIONS: MockRegion[] = [
  { slug: 'moab_ut', name: 'Moab', state_province: 'Utah', country: 'United States', continent: 'North America', description: 'Red rock paradise for mountain biking, hiking, and canyoneering', coverEmoji: '\u{1F3DC}\u{FE0F}', trailCount: 10, businessCount: 12, hasData: true },
  { slug: 'bend_or', name: 'Bend', state_province: 'Oregon', country: 'United States', continent: 'North America', description: 'Pacific Northwest hub for trail running, MTB, and skiing', coverEmoji: '\u{1F332}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'boulder_co', name: 'Boulder', state_province: 'Colorado', country: 'United States', continent: 'North America', description: 'Front Range mecca for climbing, hiking, and cycling', coverEmoji: '\u26F0\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'sedona_az', name: 'Sedona', state_province: 'Arizona', country: 'United States', continent: 'North America', description: 'Red rock trails, world-class mountain biking, and desert beauty', coverEmoji: '\u{1F3DC}\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'lake_tahoe_ca', name: 'Lake Tahoe', state_province: 'California', country: 'United States', continent: 'North America', description: 'Alpine playground for skiing, biking, and water sports', coverEmoji: '\u{1F3D4}\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'park_city_ut', name: 'Park City', state_province: 'Utah', country: 'United States', continent: 'North America', description: 'Mountain biking and skiing in the Wasatch Range', coverEmoji: '\u26F7\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'jackson_wy', name: 'Jackson Hole', state_province: 'Wyoming', country: 'United States', continent: 'North America', description: 'Grand Teton gateway for skiing, climbing, and wildlife', coverEmoji: '\u{1F3D4}\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'asheville_nc', name: 'Asheville', state_province: 'North Carolina', country: 'United States', continent: 'North America', description: 'Blue Ridge mountain biking, hiking, and craft culture', coverEmoji: '\u{1F333}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'chattanooga_tn', name: 'Chattanooga', state_province: 'Tennessee', country: 'United States', continent: 'North America', description: 'River city with world-class climbing and trail systems', coverEmoji: '\u{1F30A}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'bellingham_wa', name: 'Bellingham', state_province: 'Washington', country: 'United States', continent: 'North America', description: 'PNW mountain biking, skiing, and kayaking hub', coverEmoji: '\u{1F332}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'whistler_bc', name: 'Whistler', state_province: 'British Columbia', country: 'Canada', continent: 'North America', description: 'Legendary bike park, skiing, and alpine adventures', coverEmoji: '\u{1F3BF}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'queenstown_nz', name: 'Queenstown', state_province: 'Otago', country: 'New Zealand', continent: 'Oceania', description: 'Adventure capital — bungee, MTB, skiing, and jet boats', coverEmoji: '\u{1F3D4}\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
  { slug: 'chamonix_fr', name: 'Chamonix', state_province: 'Haute-Savoie', country: 'France', continent: 'Europe', description: 'Alpine mountaineering, skiing, and trail running', coverEmoji: '\u{1F3D4}\u{FE0F}', trailCount: 0, businessCount: 0, hasData: false },
];

// ---------------------------------------------------------------------------
// Region Highlights
// ---------------------------------------------------------------------------

export interface RegionHighlight {
  activity_slug: string;
  activity_label: string;
  activity_emoji: string;
  trail_count: number;
  business_count: number;
  active_posts_count: number;
}

export const MOCK_REGION_HIGHLIGHTS: RegionHighlight[] = [
  {
    activity_slug: 'mtb',
    activity_label: 'Mountain Biking',
    activity_emoji: '\u{1F6B5}',
    trail_count: 147,
    business_count: 18,
    active_posts_count: 34,
  },
  {
    activity_slug: 'hiking',
    activity_label: 'Hiking',
    activity_emoji: '\u{1F97E}',
    trail_count: 93,
    business_count: 11,
    active_posts_count: 22,
  },
  {
    activity_slug: 'climbing',
    activity_label: 'Rock Climbing',
    activity_emoji: '\u{1F9D7}',
    trail_count: 52,
    business_count: 7,
    active_posts_count: 15,
  },
  {
    activity_slug: 'kayaking',
    activity_label: 'Kayaking / Paddling',
    activity_emoji: '\u{1F6F6}',
    trail_count: 12,
    business_count: 5,
    active_posts_count: 9,
  },
  {
    activity_slug: 'trail_running',
    activity_label: 'Trail Running',
    activity_emoji: '\u{1F3C3}',
    trail_count: 68,
    business_count: 4,
    active_posts_count: 11,
  },
];

// ---------------------------------------------------------------------------
// Reviews
// ---------------------------------------------------------------------------

export interface MockReview {
  id: string;
  author_name: string;
  author_avatar: string | null;
  rating: number;
  title: string;
  body: string;
  entity_type: 'business' | 'trail';
  entity_id: string;
  created_at: string;
}

export const MOCK_REVIEWS: MockReview[] = [
  {
    id: 'r001',
    author_name: 'Jake Hollander',
    author_avatar: null,
    rating: 5,
    title: 'Best bike shop in Moab, period',
    body: 'Rented a Ripmo for three days and it was dialed perfectly. Staff helped me pick lines on Porcupine Rim I never would have found on my own. Trailside repair kit included at no extra charge.',
    entity_type: 'business',
    entity_id: 'b001',
    created_at: daysAgo(4),
  },
  {
    id: 'r002',
    author_name: 'Meera Patel',
    author_avatar: null,
    rating: 5,
    title: 'Slickrock lives up to the hype',
    body: 'There is nothing else like riding Slickrock. The petrified dunes give you traction at angles that feel impossible. We rode the practice loop first and then committed to the full 10-mile loop. Bring more water than you think.',
    entity_type: 'trail',
    entity_id: 't001',
    created_at: daysAgo(7),
  },
  {
    id: 'r003',
    author_name: 'Colin West',
    author_avatar: null,
    rating: 4,
    title: 'Incredible exposure on Porcupine Rim',
    body: 'The Colorado River views from the rim are worth every pedal stroke. The descent is legit gnarly though \u2014 I would rate the last two miles double-black if they stood alone. Shuttle from Poison Spider is the way to go.',
    entity_type: 'trail',
    entity_id: 't002',
    created_at: daysAgo(12),
  },
  {
    id: 'r004',
    author_name: 'Sarah Kim',
    author_avatar: null,
    rating: 5,
    title: 'Life-changing canyoneering trip',
    body: 'Booked a full-day slot canyon trip with Desert Highlights and it exceeded every expectation. Our guide knew the geology inside and out and kept us laughing the whole time. Worth every penny.',
    entity_type: 'business',
    entity_id: 'b004',
    created_at: daysAgo(3),
  },
  {
    id: 'r005',
    author_name: 'Dan Whitfield',
    author_avatar: null,
    rating: 4,
    title: 'Great breakfast before the trail',
    body: 'Hit up Red Rock Bakery before a sunrise hike at Dead Horse Point. Breakfast burrito was massive, coffee was strong, and the vibe was perfect \u2014 half the tables were people hunched over trail maps.',
    entity_type: 'business',
    entity_id: 'b009',
    created_at: daysAgo(9),
  },
  {
    id: 'r006',
    author_name: 'Ava Torres',
    author_avatar: null,
    rating: 5,
    title: 'Corona Arch is stunning',
    body: 'Short enough for a morning out, dramatic enough to feel like a real adventure. The scramble sections are fun without being scary. One of the best bang-for-your-buck hikes in the area.',
    entity_type: 'trail',
    entity_id: 't005',
    created_at: daysAgo(6),
  },
];

// ---------------------------------------------------------------------------
// Businesses
// ---------------------------------------------------------------------------

const moabHours: Record<string, string> = {
  monday: '8:00 AM - 6:00 PM',
  tuesday: '8:00 AM - 6:00 PM',
  wednesday: '8:00 AM - 6:00 PM',
  thursday: '8:00 AM - 6:00 PM',
  friday: '8:00 AM - 7:00 PM',
  saturday: '8:00 AM - 7:00 PM',
  sunday: '9:00 AM - 5:00 PM',
};

const cafeHours: Record<string, string> = {
  monday: '6:00 AM - 3:00 PM',
  tuesday: '6:00 AM - 3:00 PM',
  wednesday: '6:00 AM - 3:00 PM',
  thursday: '6:00 AM - 3:00 PM',
  friday: '6:00 AM - 3:00 PM',
  saturday: '6:00 AM - 4:00 PM',
  sunday: '7:00 AM - 2:00 PM',
};

const guideHours: Record<string, string> = {
  monday: '7:00 AM - 8:00 PM',
  tuesday: '7:00 AM - 8:00 PM',
  wednesday: '7:00 AM - 8:00 PM',
  thursday: '7:00 AM - 8:00 PM',
  friday: '7:00 AM - 8:00 PM',
  saturday: '6:00 AM - 9:00 PM',
  sunday: '6:00 AM - 9:00 PM',
};

const hostelHours: Record<string, string> = {
  monday: '7:00 AM - 10:00 PM',
  tuesday: '7:00 AM - 10:00 PM',
  wednesday: '7:00 AM - 10:00 PM',
  thursday: '7:00 AM - 10:00 PM',
  friday: '7:00 AM - 11:00 PM',
  saturday: '7:00 AM - 11:00 PM',
  sunday: '7:00 AM - 10:00 PM',
};

export const MOCK_BUSINESSES = [
  // ---- Spotlight: Founding ----
  {
    id: 'b001',
    name: 'Poison Spider Bicycles',
    slug: 'poison-spider-bicycles',
    description:
      'Moab\u2019s original mountain bike shop, open since 1989. Full-suspension rentals, expert trail advice, and a mechanic crew that has ridden every line in the valley. Home of the legendary Slickrock pre-ride tune-up.',
    category: 'bike_shop',
    subcategories: ['rental', 'repair', 'retail'],
    activity_types: ['mtb', 'road_cycling'],
    address: '497 N Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5774,
    lng: -109.5493,
    phone: '+1 435-259-7882',
    email: 'info@poisonspiderbicycles.com',
    website_url: 'https://poisonspiderbicycles.com',
    booking_url: 'https://poisonspiderbicycles.com/rentals',
    instagram_handle: 'poisonspiderbicycles',
    facebook_url: 'https://facebook.com/poisonspiderbicycles',
    tripadvisor_url: null,
    yelp_url: 'https://yelp.com/biz/poison-spider-bicycles-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/abc123',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: '+14352597882',
    hours: moabHours,
    photos: ['/images/placeholder-bike_shop-1.jpg', '/images/placeholder-bike_shop-2.jpg'],
    cover_photo_url: '/images/placeholder-bike_shop.jpg',
    rating: 4.8,
    review_count: 312,
    is_spotlight: true,
    spotlight_tier: 'founding',
    special_offer: '15% off multi-day rentals booked through Cairn Connect',
    special_offer_expires_at: daysFromNow(45),
    is_claimed: true,
    claimed_by: 'u_owner_001',
    tags: ['bike rental', 'full suspension', 'trail advice', 'repairs', 'Slickrock experts', 'e-bike rental'],
    currency: 'USD',
    price_range: { min: 65, max: 125, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(180),
    updated_at: daysAgo(1),
  },

  // ---- Spotlight: Premium ----
  {
    id: 'b002',
    name: 'Rim Cyclery',
    slug: 'rim-cyclery',
    description:
      'Family-owned bike shop on Center Street with 30+ years in Moab. Known for their hand-built wheels and honest sizing advice. They carry Yeti, Santa Cruz, and Guerrilla Gravity demos for full-day trail tests.',
    category: 'bike_shop',
    subcategories: ['rental', 'repair', 'retail', 'demo'],
    activity_types: ['mtb', 'road_cycling'],
    address: '94 W 100 N',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5735,
    lng: -109.5516,
    phone: '+1 435-259-5333',
    email: 'shop@rimcyclery.com',
    website_url: 'https://rimcyclery.com',
    booking_url: 'https://rimcyclery.com/book',
    instagram_handle: 'rimcyclery',
    facebook_url: 'https://facebook.com/rimcyclery',
    tripadvisor_url: 'https://tripadvisor.com/rimcyclery',
    yelp_url: 'https://yelp.com/biz/rim-cyclery-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/def456',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: '+14352594321',
    hours: moabHours,
    photos: ['/images/placeholder-bike_shop-3.jpg'],
    cover_photo_url: '/images/placeholder-bike_shop.jpg',
    rating: 4.7,
    review_count: 248,
    is_spotlight: true,
    spotlight_tier: 'premium',
    special_offer: 'Free hydration pack with any 3+ day rental',
    special_offer_expires_at: daysFromNow(30),
    is_claimed: true,
    claimed_by: 'u_owner_002',
    tags: ['demo bikes', 'wheel building', 'Santa Cruz', 'Yeti', 'family-owned', 'trail maps'],
    currency: 'USD',
    price_range: { min: 75, max: 150, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(210),
    updated_at: daysAgo(2),
  },

  // ---- Spotlight: Standard ----
  {
    id: 'b003',
    name: 'Moab Desert Adventures',
    slug: 'moab-desert-adventures',
    description:
      'Small-group guided experiences across the Moab backcountry. Canyoneering, 4x4 tours, guided MTB descents, and multi-day packrafting trips down the Colorado. All guides are Wilderness First Responder certified.',
    category: 'guide_service',
    subcategories: ['canyoneering', '4x4', 'mtb', 'packrafting'],
    activity_types: ['hiking', 'mtb', 'kayaking', 'climbing'],
    address: '415 N Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5761,
    lng: -109.5495,
    phone: '+1 435-260-2404',
    email: 'book@moabdesertadventures.com',
    website_url: 'https://moabdesertadventures.com',
    booking_url: 'https://moabdesertadventures.com/book',
    instagram_handle: 'moabdesertadventures',
    facebook_url: 'https://facebook.com/moabdesertadventures',
    tripadvisor_url: 'https://tripadvisor.com/moabdesertadventures',
    yelp_url: null,
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/ghi789',
    youtube_url: 'https://youtube.com/@moabdesertadventures',
    strava_segment_url: null,
    whatsapp: null,
    hours: guideHours,
    photos: ['/images/placeholder-guide_service-1.jpg', '/images/placeholder-guide_service-2.jpg'],
    cover_photo_url: '/images/placeholder-guide_service.jpg',
    rating: 4.9,
    review_count: 187,
    is_spotlight: true,
    spotlight_tier: 'standard',
    special_offer: '$50 off any canyoneering trip when you mention Cairn Connect',
    special_offer_expires_at: daysFromNow(60),
    is_claimed: true,
    claimed_by: 'u_owner_003',
    tags: ['canyoneering', 'guided tours', 'small group', 'WFR certified', 'packrafting', 'backcountry'],
    currency: 'USD',
    price_range: { min: 125, max: 299, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(150),
    updated_at: daysAgo(1),
  },

  // ---- Regular businesses ----
  {
    id: 'b004',
    name: 'Desert Highlights',
    slug: 'desert-highlights',
    description:
      'Premier canyoneering and climbing guides in Moab since 2001. Specializing in technical slot canyons, tower climbs, and multi-pitch desert routes. Small groups, top-of-the-line gear, and an unwavering commitment to Leave No Trace.',
    category: 'guide_service',
    subcategories: ['canyoneering', 'climbing', 'rappelling'],
    activity_types: ['climbing', 'hiking'],
    address: '50 E Center St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5727,
    lng: -109.5483,
    phone: '+1 435-259-4433',
    email: 'hello@deserthighlights.com',
    website_url: 'https://deserthighlights.com',
    booking_url: 'https://deserthighlights.com/trips',
    instagram_handle: 'deserthighlights',
    facebook_url: 'https://facebook.com/deserthighlights',
    tripadvisor_url: 'https://tripadvisor.com/deserthighlights',
    yelp_url: null,
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/jkl012',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: guideHours,
    photos: ['/images/placeholder-guide_service-3.jpg'],
    cover_photo_url: '/images/placeholder-guide_service.jpg',
    rating: 4.9,
    review_count: 224,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_004',
    tags: ['canyoneering', 'rock climbing', 'slot canyons', 'rappelling', 'Leave No Trace'],
    currency: 'USD',
    price_range: { min: 149, max: 349, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(160),
    updated_at: daysAgo(5),
  },
  {
    id: 'b005',
    name: 'Coyote Shuttle',
    slug: 'coyote-shuttle',
    description:
      'Reliable bike and hiker shuttle service covering every major trailhead in the Moab area. Porcupine Rim, Whole Enchilada, Kokopelli \u2014 they run them all. Reservations recommended but walk-ups welcome when seats are available.',
    category: 'bike_shuttle',
    subcategories: ['trailhead shuttle', 'airport transfer'],
    activity_types: ['mtb', 'hiking', 'trail_running'],
    address: '197 S Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5701,
    lng: -109.5502,
    phone: '+1 435-260-2227',
    email: 'rides@coyoteshuttle.com',
    website_url: 'https://coyoteshuttle.com',
    booking_url: 'https://coyoteshuttle.com/schedule',
    instagram_handle: 'coyoteshuttlemoab',
    facebook_url: 'https://facebook.com/coyoteshuttlemoab',
    tripadvisor_url: null,
    yelp_url: 'https://yelp.com/biz/coyote-shuttle-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/mno345',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: {
      monday: '6:00 AM - 7:00 PM',
      tuesday: '6:00 AM - 7:00 PM',
      wednesday: '6:00 AM - 7:00 PM',
      thursday: '6:00 AM - 7:00 PM',
      friday: '6:00 AM - 8:00 PM',
      saturday: '5:30 AM - 8:00 PM',
      sunday: '5:30 AM - 7:00 PM',
    },
    photos: ['/images/placeholder-bike_shuttle-1.jpg'],
    cover_photo_url: '/images/placeholder-bike_shuttle.jpg',
    rating: 4.6,
    review_count: 134,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: '10% off Whole Enchilada shuttles on weekdays',
    special_offer_expires_at: daysFromNow(21),
    is_claimed: true,
    claimed_by: 'u_owner_005',
    tags: ['bike shuttle', 'Porcupine Rim', 'Whole Enchilada', 'Kokopelli', 'hiker shuttle'],
    currency: 'USD',
    price_range: { min: 35, max: 55, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(200),
    updated_at: daysAgo(3),
  },
  {
    id: 'b006',
    name: 'Moab Gear Trader',
    slug: 'moab-gear-trader',
    description:
      'Consignment outdoor gear shop stocked with gently used packs, climbing hardware, camp stoves, and the occasional vintage Chouinard piece. Great place to gear up on a budget or offload equipment at the end of a trip.',
    category: 'outdoor_gear_shop',
    subcategories: ['consignment', 'used gear', 'retail'],
    activity_types: ['hiking', 'climbing', 'camping'],
    address: '78 N Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5742,
    lng: -109.5498,
    phone: '+1 435-259-4327',
    email: 'trade@moabgeartrader.com',
    website_url: 'https://moabgeartrader.com',
    booking_url: null,
    instagram_handle: 'moabgeartrader',
    facebook_url: 'https://facebook.com/moabgeartrader',
    tripadvisor_url: null,
    yelp_url: 'https://yelp.com/biz/moab-gear-trader',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/pqr678',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: moabHours,
    photos: ['/images/placeholder-outdoor_gear_shop-1.jpg'],
    cover_photo_url: '/images/placeholder-outdoor_gear_shop.jpg',
    rating: 4.5,
    review_count: 97,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_006',
    tags: ['used gear', 'consignment', 'climbing hardware', 'camp gear', 'budget-friendly'],
    currency: 'USD',
    price_range: { min: 15, max: 85, unit: 'flat' },
    is_active: true,
    created_at: daysAgo(190),
    updated_at: daysAgo(8),
  },
  {
    id: 'b007',
    name: 'Red River Canoe Company',
    slug: 'red-river-canoe-company',
    description:
      'Kayak, canoe, and stand-up paddleboard rentals on the Colorado River. Half-day and full-day packages with all the gear you need. Guided sunset paddles available Thursday through Sunday.',
    category: 'kayak_sup',
    subcategories: ['kayak rental', 'SUP rental', 'canoe rental', 'guided paddles'],
    activity_types: ['kayaking', 'standup_paddle'],
    address: '100 W Kane Creek Blvd',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5688,
    lng: -109.5531,
    phone: '+1 435-259-7722',
    email: 'paddle@redrivercanoe.com',
    website_url: 'https://redrivercanoe.com',
    booking_url: 'https://redrivercanoe.com/reserve',
    instagram_handle: 'redrivercanoe',
    facebook_url: 'https://facebook.com/redrivercanoe',
    tripadvisor_url: 'https://tripadvisor.com/redrivercanoe',
    yelp_url: null,
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/stu901',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: {
      monday: '7:00 AM - 6:00 PM',
      tuesday: '7:00 AM - 6:00 PM',
      wednesday: '7:00 AM - 6:00 PM',
      thursday: '7:00 AM - 7:00 PM',
      friday: '7:00 AM - 7:00 PM',
      saturday: '6:30 AM - 7:00 PM',
      sunday: '6:30 AM - 6:00 PM',
    },
    photos: ['/images/placeholder-kayak_sup-1.jpg', '/images/placeholder-kayak_sup-2.jpg'],
    cover_photo_url: '/images/placeholder-kayak_sup.jpg',
    rating: 4.7,
    review_count: 163,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_007',
    tags: ['kayak rental', 'SUP', 'Colorado River', 'sunset paddles', 'canoe', 'family-friendly'],
    currency: 'USD',
    price_range: { min: 45, max: 95, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(170),
    updated_at: daysAgo(4),
  },
  {
    id: 'b008',
    name: 'Canyon Voyages Adventure Co.',
    slug: 'canyon-voyages-adventure-co',
    description:
      'Full-service outfitter running rafting, kayaking, and combination 4x4/river trips. Multi-day expeditions through Cataract Canyon and calm-water floats for families. On-site gear shop and espresso bar.',
    category: 'outfitter',
    subcategories: ['rafting', 'kayaking', '4x4', 'multi-day trips'],
    activity_types: ['kayaking', 'whitewater', 'camping'],
    address: '211 N Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5752,
    lng: -109.5497,
    phone: '+1 435-259-6007',
    email: 'info@canyonvoyages.com',
    website_url: 'https://canyonvoyages.com',
    booking_url: 'https://canyonvoyages.com/book',
    instagram_handle: 'canyonvoyages',
    facebook_url: 'https://facebook.com/canyonvoyages',
    tripadvisor_url: 'https://tripadvisor.com/canyonvoyages',
    yelp_url: 'https://yelp.com/biz/canyon-voyages-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/vwx234',
    youtube_url: 'https://youtube.com/@canyonvoyages',
    strava_segment_url: null,
    whatsapp: null,
    hours: guideHours,
    photos: ['/images/placeholder-outfitter-1.jpg', '/images/placeholder-outfitter-2.jpg'],
    cover_photo_url: '/images/placeholder-outfitter.jpg',
    rating: 4.8,
    review_count: 291,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: 'Book a Cataract Canyon trip and get a free dry bag',
    special_offer_expires_at: daysFromNow(14),
    is_claimed: true,
    claimed_by: 'u_owner_008',
    tags: ['rafting', 'Cataract Canyon', 'multi-day', 'family rafting', 'Colorado River', 'gear shop'],
    currency: 'USD',
    price_range: { min: 89, max: 399, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(220),
    updated_at: daysAgo(2),
  },
  {
    id: 'b009',
    name: 'Red Rock Bakery & Cafe',
    slug: 'red-rock-bakery-cafe',
    description:
      'Early-morning fuel stop for riders, hikers, and climbers. Scratch-made pastries, breakfast burritos the size of your forearm, and espresso drinks. Outdoor patio with a bike rack and a trail conditions chalkboard updated daily.',
    category: 'trailhead_cafe',
    subcategories: ['bakery', 'coffee', 'breakfast'],
    activity_types: ['hiking', 'mtb', 'climbing', 'trail_running'],
    address: '74 S Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5718,
    lng: -109.5500,
    phone: '+1 435-259-3941',
    email: 'eat@redrockbakery.com',
    website_url: 'https://redrockbakery.com',
    booking_url: null,
    instagram_handle: 'redrockbakerymoab',
    facebook_url: 'https://facebook.com/redrockbakerymoab',
    tripadvisor_url: 'https://tripadvisor.com/redrockbakery',
    yelp_url: 'https://yelp.com/biz/red-rock-bakery-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/yza567',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: cafeHours,
    photos: ['/images/placeholder-trailhead_cafe-1.jpg'],
    cover_photo_url: '/images/placeholder-trailhead_cafe.jpg',
    rating: 4.6,
    review_count: 178,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_009',
    tags: ['breakfast', 'coffee', 'pastries', 'bike rack', 'trail conditions', 'early morning'],
    currency: 'USD',
    price_range: { min: 8, max: 18, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(195),
    updated_at: daysAgo(1),
  },
  {
    id: 'b010',
    name: 'Slickrock Gear Rental',
    slug: 'slickrock-gear-rental',
    description:
      'Rent everything you forgot to pack: tents, sleeping bags, coolers, camp chairs, bear canisters, and more. Free delivery to any campground within 10 miles of Moab. Packages available for multi-day trips.',
    category: 'gear_rental',
    subcategories: ['camping gear', 'delivery', 'packages'],
    activity_types: ['camping', 'hiking', 'kayaking'],
    address: '330 E Center St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5729,
    lng: -109.5461,
    phone: '+1 435-259-1188',
    email: 'rent@slickrockgear.com',
    website_url: 'https://slickrockgear.com',
    booking_url: 'https://slickrockgear.com/reserve',
    instagram_handle: 'slickrockgear',
    facebook_url: null,
    tripadvisor_url: null,
    yelp_url: 'https://yelp.com/biz/slickrock-gear-rental-moab',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/bcd890',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: moabHours,
    photos: ['/images/placeholder-gear_rental-1.jpg'],
    cover_photo_url: '/images/placeholder-gear_rental.jpg',
    rating: 4.4,
    review_count: 62,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: 'Free campground delivery on orders over $75',
    special_offer_expires_at: daysFromNow(30),
    is_claimed: true,
    claimed_by: 'u_owner_010',
    tags: ['camping gear', 'tent rental', 'free delivery', 'cooler rental', 'trip packages'],
    currency: 'USD',
    price_range: { min: 25, max: 75, unit: 'flat' },
    is_active: true,
    created_at: daysAgo(140),
    updated_at: daysAgo(6),
  },
  {
    id: 'b011',
    name: 'Lazy Lizard International Hostel',
    slug: 'lazy-lizard-hostel',
    description:
      'The legendary budget base camp for Moab adventurers. Dorm beds, private cabins, a hot tub under the stars, and a communal kitchen where half the conversations start with "So what trail did you ride today?" Bike wash station and secure storage included.',
    category: 'adventure_hostel',
    subcategories: ['dorms', 'cabins', 'camping'],
    activity_types: ['mtb', 'hiking', 'climbing', 'kayaking'],
    address: '1213 S Hwy 191',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5624,
    lng: -109.5478,
    phone: '+1 435-259-6057',
    email: 'stay@lazylizardhostel.com',
    website_url: 'https://lazylizardhostel.com',
    booking_url: 'https://lazylizardhostel.com/book',
    instagram_handle: 'lazylizardmoab',
    facebook_url: 'https://facebook.com/lazylizardhostel',
    tripadvisor_url: 'https://tripadvisor.com/lazylizardhostel',
    yelp_url: null,
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/efg123',
    youtube_url: null,
    strava_segment_url: null,
    whatsapp: null,
    hours: hostelHours,
    photos: ['/images/placeholder-adventure_hostel-1.jpg', '/images/placeholder-adventure_hostel-2.jpg'],
    cover_photo_url: '/images/placeholder-adventure_hostel.jpg',
    rating: 4.3,
    review_count: 415,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_011',
    tags: ['hostel', 'budget', 'hot tub', 'bike wash', 'communal kitchen', 'backpacker'],
    currency: 'USD',
    price_range: { min: 15, max: 65, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(240),
    updated_at: daysAgo(2),
  },
  {
    id: 'b012',
    name: 'Moab Cliffs & Canyons',
    slug: 'moab-cliffs-and-canyons',
    description:
      'Guided climbing, canyoneering, and rappelling adventures for every skill level. Half-day intro clinics for beginners, multi-pitch desert tower ascents for seasoned climbers, and everything in between. AMGA-accredited guides.',
    category: 'guide_service',
    subcategories: ['climbing', 'canyoneering', 'rappelling', 'clinics'],
    activity_types: ['climbing', 'hiking'],
    address: '253 N Main St',
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    postal_code: '84532',
    lat: 38.5756,
    lng: -109.5496,
    phone: '+1 435-259-3317',
    email: 'climb@moabcliffs.com',
    website_url: 'https://moabcliffs.com',
    booking_url: 'https://moabcliffs.com/adventures',
    instagram_handle: 'moabcliffscanyons',
    facebook_url: 'https://facebook.com/moabcliffscanyons',
    tripadvisor_url: 'https://tripadvisor.com/moabcliffscanyons',
    yelp_url: 'https://yelp.com/biz/moab-cliffs-and-canyons',
    alltrails_url: null,
    google_maps_url: 'https://goo.gl/maps/hij456',
    youtube_url: 'https://youtube.com/@moabcliffs',
    strava_segment_url: null,
    whatsapp: null,
    hours: guideHours,
    photos: ['/images/placeholder-guide_service-4.jpg'],
    cover_photo_url: '/images/placeholder-guide_service.jpg',
    rating: 4.9,
    review_count: 356,
    is_spotlight: false,
    spotlight_tier: null,
    special_offer: null,
    special_offer_expires_at: null,
    is_claimed: true,
    claimed_by: 'u_owner_012',
    tags: ['rock climbing', 'canyoneering', 'AMGA', 'beginner-friendly', 'desert towers', 'rappelling'],
    currency: 'USD',
    price_range: { min: 99, max: 275, unit: 'per_person' },
    is_active: true,
    created_at: daysAgo(230),
    updated_at: daysAgo(3),
  },
];

// ---------------------------------------------------------------------------
// Trails
// ---------------------------------------------------------------------------

export const MOCK_TRAILS = [
  {
    id: 't001',
    name: 'Slickrock Trail',
    slug: 'slickrock-trail',
    description:
      'The trail that put Moab on the mountain biking map. 10.5 miles of petrified sand dunes with traction you have to feel to believe. Painted white dashes mark the route across undulating Navajo Sandstone. Incredibly exposed \u2014 bring sun protection and at least 3 liters of water.',
    activity_types: ['mtb', 'hiking'],
    difficulty: 'black',
    difficulty_label: 'Advanced',
    technical_rating: 4,
    distance_meters: 16900,
    elevation_gain_meters: 396,
    elevation_loss_meters: 396,
    max_elevation_meters: 1524,
    min_elevation_meters: 1402,
    trail_type: 'loop',
    surface_type: ['sandstone', 'slickrock'],
    lat: 38.5912,
    lng: -109.5128,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(1),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 180,
    rating: 4.8,
    review_count: 1243,
    ride_count: 18742,
    photos: ['/images/placeholder-trail-slickrock-1.jpg', '/images/placeholder-trail-slickrock-2.jpg'],
    cover_photo_url: '/images/placeholder-trail-slickrock.jpg',
    best_seasons: ['spring', 'fall'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(1),
  },
  {
    id: 't002',
    name: 'Porcupine Rim',
    slug: 'porcupine-rim',
    description:
      'One of the premier point-to-point descents in the world. 14 miles of singletrack starting above the La Sal Mountains with massive exposure along the Colorado River canyon rim. The final descent into the valley is loose, steep, and absolutely legendary.',
    activity_types: ['mtb'],
    difficulty: 'double_black',
    difficulty_label: 'Expert',
    technical_rating: 5,
    distance_meters: 22530,
    elevation_gain_meters: 244,
    elevation_loss_meters: 914,
    max_elevation_meters: 1920,
    min_elevation_meters: 1219,
    trail_type: 'point_to_point',
    surface_type: ['singletrack', 'rock', 'sand'],
    lat: 38.5955,
    lng: -109.4432,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(2),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 240,
    rating: 4.9,
    review_count: 876,
    ride_count: 11234,
    photos: ['/images/placeholder-trail-porcupine-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-porcupine.jpg',
    best_seasons: ['spring', 'fall'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(2),
  },
  {
    id: 't003',
    name: 'Poison Spider Mesa',
    slug: 'poison-spider-mesa',
    description:
      'Technical out-and-back across a high mesa with sweeping views of the Colorado River, Behind the Rocks, and the La Sal Mountains. The Portal Trail descent option is a no-fall-zone cliff edge that separates the brave from the bold.',
    activity_types: ['mtb', 'hiking'],
    difficulty: 'double_black',
    difficulty_label: 'Expert',
    technical_rating: 5,
    distance_meters: 14480,
    elevation_gain_meters: 488,
    elevation_loss_meters: 488,
    max_elevation_meters: 1585,
    min_elevation_meters: 1219,
    trail_type: 'out_and_back',
    surface_type: ['slickrock', 'rock', 'sand'],
    lat: 38.5622,
    lng: -109.5887,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(3),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 210,
    rating: 4.7,
    review_count: 532,
    ride_count: 7891,
    photos: ['/images/placeholder-trail-poison-spider-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-poison-spider.jpg',
    best_seasons: ['spring', 'fall'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(3),
  },
  {
    id: 't004',
    name: 'Bartlett Wash',
    slug: 'bartlett-wash',
    description:
      'Wide-open sandstone playground perfect for progressing your slickrock skills. No marked trail \u2014 just acres of smooth Navajo Sandstone with natural features ranging from gentle rollers to steep drop-offs. Bring a friend, explore freely, and session the features you find.',
    activity_types: ['mtb'],
    difficulty: 'blue',
    difficulty_label: 'Intermediate',
    technical_rating: 3,
    distance_meters: 8050,
    elevation_gain_meters: 122,
    elevation_loss_meters: 122,
    max_elevation_meters: 1463,
    min_elevation_meters: 1402,
    trail_type: 'network',
    surface_type: ['slickrock', 'sandstone'],
    lat: 38.6421,
    lng: -109.5634,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(5),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 120,
    rating: 4.5,
    review_count: 289,
    ride_count: 5432,
    photos: ['/images/placeholder-trail-bartlett-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-bartlett.jpg',
    best_seasons: ['spring', 'fall', 'winter'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(5),
  },
  {
    id: 't005',
    name: 'Corona Arch Trail',
    slug: 'corona-arch-trail',
    description:
      'Short but spectacular hiking trail to one of the largest free-standing arches in Utah. The route crosses railroad tracks, traverses slickrock, and includes a fun scramble section with fixed cables and a short ladder. The arch itself is enormous and uncrowded compared to Arches NP.',
    activity_types: ['hiking', 'trail_running'],
    difficulty: 'blue',
    difficulty_label: 'Intermediate',
    technical_rating: 2,
    distance_meters: 4828,
    elevation_gain_meters: 137,
    elevation_loss_meters: 137,
    max_elevation_meters: 1341,
    min_elevation_meters: 1244,
    trail_type: 'out_and_back',
    surface_type: ['slickrock', 'rock', 'dirt'],
    lat: 38.5808,
    lng: -109.6204,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(1),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 90,
    rating: 4.7,
    review_count: 1567,
    ride_count: 0,
    photos: ['/images/placeholder-trail-corona-1.jpg', '/images/placeholder-trail-corona-2.jpg'],
    cover_photo_url: '/images/placeholder-trail-corona.jpg',
    best_seasons: ['spring', 'fall', 'winter'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(1),
  },
  {
    id: 't006',
    name: 'Fisher Towers Trail',
    slug: 'fisher-towers-trail',
    description:
      'A surreal hike through towering Cutler sandstone formations that look like drip castles from another planet. The trail weaves between the towers with views of the Colorado River valley and the La Sal range. Popular with photographers, climbers scope their routes from here.',
    activity_types: ['hiking', 'trail_running'],
    difficulty: 'blue',
    difficulty_label: 'Intermediate',
    technical_rating: 2,
    distance_meters: 7080,
    elevation_gain_meters: 224,
    elevation_loss_meters: 224,
    max_elevation_meters: 1524,
    min_elevation_meters: 1372,
    trail_type: 'out_and_back',
    surface_type: ['dirt', 'rock', 'sand'],
    lat: 38.7265,
    lng: -109.3079,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(4),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 150,
    rating: 4.6,
    review_count: 987,
    ride_count: 0,
    photos: ['/images/placeholder-trail-fisher-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-fisher.jpg',
    best_seasons: ['spring', 'fall'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(4),
  },
  {
    id: 't007',
    name: 'Hidden Valley Trail',
    slug: 'hidden-valley-trail',
    description:
      'A local favorite that climbs steeply through a notch in the Moab Rim before dropping into a secluded valley ringed by red rock walls. The upper valley connects to a network of slickrock riding. A quieter alternative to the Sand Flats trails on busy weekends.',
    activity_types: ['mtb', 'hiking'],
    difficulty: 'blue',
    difficulty_label: 'Intermediate',
    technical_rating: 3,
    distance_meters: 5310,
    elevation_gain_meters: 198,
    elevation_loss_meters: 198,
    max_elevation_meters: 1463,
    min_elevation_meters: 1310,
    trail_type: 'loop',
    surface_type: ['singletrack', 'slickrock', 'dirt'],
    lat: 38.5563,
    lng: -109.5618,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(2),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 90,
    rating: 4.4,
    review_count: 345,
    ride_count: 4210,
    photos: ['/images/placeholder-trail-hidden-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-hidden.jpg',
    best_seasons: ['spring', 'fall', 'winter'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(2),
  },
  {
    id: 't008',
    name: 'Amasa Back',
    slug: 'amasa-back',
    description:
      'Challenging mesa-top ride with the optional Cliffhanger add-on that delivers some of the most technical and exposed riding in Moab. The climb up the back side is relentless, but the views of Hurrah Pass and the Colorado River from the top are staggering.',
    activity_types: ['mtb'],
    difficulty: 'black',
    difficulty_label: 'Advanced',
    technical_rating: 4,
    distance_meters: 15610,
    elevation_gain_meters: 457,
    elevation_loss_meters: 457,
    max_elevation_meters: 1524,
    min_elevation_meters: 1219,
    trail_type: 'out_and_back',
    surface_type: ['slickrock', 'rock', 'singletrack'],
    lat: 38.5532,
    lng: -109.5865,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'caution',
    condition_updated_at: daysAgo(1),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 210,
    rating: 4.8,
    review_count: 612,
    ride_count: 8923,
    photos: ['/images/placeholder-trail-amasa-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-amasa.jpg',
    best_seasons: ['spring', 'fall'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(1),
  },
  {
    id: 't009',
    name: 'Gemini Bridges',
    slug: 'gemini-bridges',
    description:
      'A long, mostly downhill ride from the top access that passes two massive natural rock bridges spanning a deep canyon. The route is mostly doubletrack with some singletrack connectors. Excellent intermediate ride and one of the best shuttle-assisted trails in the area.',
    activity_types: ['mtb', 'hiking'],
    difficulty: 'green',
    difficulty_label: 'Beginner',
    technical_rating: 2,
    distance_meters: 22530,
    elevation_gain_meters: 152,
    elevation_loss_meters: 610,
    max_elevation_meters: 1646,
    min_elevation_meters: 1219,
    trail_type: 'point_to_point',
    surface_type: ['doubletrack', 'dirt', 'singletrack'],
    lat: 38.6318,
    lng: -109.6241,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(3),
    requires_permit: false,
    permit_id: null,
    estimated_duration_minutes: 180,
    rating: 4.3,
    review_count: 567,
    ride_count: 9876,
    photos: ['/images/placeholder-trail-gemini-1.jpg'],
    cover_photo_url: '/images/placeholder-trail-gemini.jpg',
    best_seasons: ['spring', 'fall', 'winter'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(3),
  },
  {
    id: 't010',
    name: 'Dead Horse Point Rim Trail',
    slug: 'dead-horse-point-rim-trail',
    description:
      'A stunning loop along the edge of Dead Horse Point State Park with jaw-dropping overlooks of the Colorado River gooseneck 2,000 feet below. Mostly smooth singletrack with a few rocky sections. One of the most photogenic trails in Utah \u2014 bring your camera for golden hour.',
    activity_types: ['mtb', 'hiking', 'trail_running'],
    difficulty: 'green',
    difficulty_label: 'Beginner',
    technical_rating: 2,
    distance_meters: 14160,
    elevation_gain_meters: 91,
    elevation_loss_meters: 91,
    max_elevation_meters: 1829,
    min_elevation_meters: 1768,
    trail_type: 'loop',
    surface_type: ['singletrack', 'dirt', 'rock'],
    lat: 38.4829,
    lng: -109.7317,
    route_geojson: null,
    city: 'Moab',
    state_province: 'Utah',
    country: 'United States',
    country_code: 'US',
    current_condition: 'open',
    condition_updated_at: daysAgo(1),
    requires_permit: true,
    permit_id: 'permit_dhp',
    permit_cost: 15,
    estimated_duration_minutes: 150,
    rating: 4.7,
    review_count: 1102,
    ride_count: 12345,
    photos: ['/images/placeholder-trail-deadhorse-1.jpg', '/images/placeholder-trail-deadhorse-2.jpg'],
    cover_photo_url: '/images/placeholder-trail-deadhorse.jpg',
    best_seasons: ['spring', 'fall', 'winter'],
    source: 'community',
    is_active: true,
    created_at: daysAgo(365),
    updated_at: daysAgo(1),
  },
];

// ---------------------------------------------------------------------------
// Activity Posts
// ---------------------------------------------------------------------------

export const MOCK_ACTIVITY_POSTS = [
  {
    id: 'ap001',
    user_id: 'u001',
    post_type: 'im_going',
    activity_type: 'mtb',
    title: 'Sunrise Slickrock session',
    description:
      'Hitting Slickrock at first light before the heat kicks in. Planning to ride the full loop. Happy to have company if you can keep a moderate pace.',
    location_name: 'Slickrock Trail, Sand Flats',
    lat: 38.5912,
    lng: -109.5128,
    trail_id: 't001',
    activity_date: daysFromNow(3),
    activity_end_date: null,
    skill_level: 'intermediate',
    max_participants: 4,
    current_participants: 1,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: null,
    gear_required: ['full-suspension bike', 'helmet', '3L water minimum'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 42,
    created_at: daysAgo(1),
    user_display_name: 'Tyler R.',
    user_avatar: 'TR',
  },
  {
    id: 'ap002',
    user_id: 'u002',
    post_type: 'open_permit',
    activity_type: 'kayaking',
    title: '2 open spots \u2014 Cataract Canyon 3-day',
    description:
      'Our group scored a 3-day Cataract Canyon permit and two people dropped. Looking for experienced paddlers who are comfortable in Class III-IV whitewater. All shared gear provided, just bring your PFD and personal kit.',
    location_name: 'Cataract Canyon, Colorado River',
    lat: 38.4250,
    lng: -109.8800,
    trail_id: null,
    activity_date: daysFromNow(12),
    activity_end_date: daysFromNow(14),
    skill_level: 'advanced',
    max_participants: 8,
    current_participants: 6,
    permit_required: true,
    permit_type: 'Cataract Canyon River Permit',
    permit_slots_available: 2,
    cost_share: 185,
    gear_required: ['PFD', 'dry bag', 'sleeping bag', 'personal medications'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 118,
    created_at: daysAgo(3),
    user_display_name: 'Kira M.',
    user_avatar: 'KM',
  },
  {
    id: 'ap003',
    user_id: 'u003',
    post_type: 'lfg',
    activity_type: 'climbing',
    title: 'Looking for a belay partner at Wall Street',
    description:
      'In town for the week and looking for someone to trade leads at the Wall Street climbing area. I climb solid 5.10 trad and have a full rack. Morning sessions preferred.',
    location_name: 'Wall Street Climbing Area',
    lat: 38.5720,
    lng: -109.5930,
    trail_id: null,
    activity_date: daysFromNow(2),
    activity_end_date: daysFromNow(6),
    skill_level: 'advanced',
    max_participants: 2,
    current_participants: 1,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: null,
    gear_required: ['climbing shoes', 'harness', 'helmet', 'belay device'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 67,
    created_at: daysAgo(1),
    user_display_name: 'Sam B.',
    user_avatar: 'SB',
  },
  {
    id: 'ap004',
    user_id: 'u004',
    post_type: 'im_going',
    activity_type: 'hiking',
    title: 'Fisher Towers sunset hike',
    description:
      'Driving out to Fisher Towers for a late afternoon hike to catch the sunset lighting up the towers. Easy pace, all levels welcome. Meeting at the trailhead parking lot.',
    location_name: 'Fisher Towers Trailhead',
    lat: 38.7265,
    lng: -109.3079,
    trail_id: 't006',
    activity_date: daysFromNow(5),
    activity_end_date: null,
    skill_level: 'beginner',
    max_participants: 8,
    current_participants: 3,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: null,
    gear_required: ['headlamp', 'water', 'layers'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 31,
    created_at: daysAgo(2),
    user_display_name: 'Jess L.',
    user_avatar: 'JL',
  },
  {
    id: 'ap005',
    user_id: 'u005',
    post_type: 'lfg',
    activity_type: 'mtb',
    title: 'Porcupine Rim \u2014 need a shuttle buddy',
    description:
      'Want to ride Porcupine Rim this weekend but need someone to split the shuttle cost with. I ride advanced-level tech and am comfortable with exposure. Thinking Saturday morning departure.',
    location_name: 'Porcupine Rim Trail',
    lat: 38.5955,
    lng: -109.4432,
    trail_id: 't002',
    activity_date: daysFromNow(8),
    activity_end_date: null,
    skill_level: 'expert',
    max_participants: 3,
    current_participants: 1,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: 25,
    gear_required: ['full-suspension bike', 'full-face helmet', 'knee pads', 'water'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 89,
    created_at: daysAgo(1),
    user_display_name: 'Marco D.',
    user_avatar: 'MD',
  },
  {
    id: 'ap006',
    user_id: 'u006',
    post_type: 'open_permit',
    activity_type: 'hiking',
    title: 'The Fiery Furnace \u2014 1 permit slot open',
    description:
      'Got a ranger-guided Fiery Furnace permit for next Saturday and have one extra slot. The hike involves scrambling, narrow passages, and route-finding through a sandstone labyrinth. Moderate fitness required.',
    location_name: 'Fiery Furnace, Arches NP',
    lat: 38.7465,
    lng: -109.5775,
    trail_id: null,
    activity_date: daysFromNow(10),
    activity_end_date: null,
    skill_level: 'intermediate',
    max_participants: 4,
    current_participants: 3,
    permit_required: true,
    permit_type: 'Arches NP Fiery Furnace Permit',
    permit_slots_available: 1,
    cost_share: 10,
    gear_required: ['sturdy boots', 'water', 'sun hat'],
    contact_method: 'email',
    status: 'active',
    view_count: 156,
    created_at: daysAgo(4),
    user_display_name: 'Ali T.',
    user_avatar: 'AT',
  },
  {
    id: 'ap007',
    user_id: 'u007',
    post_type: 'im_going',
    activity_type: 'trail_running',
    title: 'Corona Arch morning run',
    description:
      'Quick morning trail run out to Corona Arch and back before work. Leaving from the trailhead at 6:30 AM. Moderate pace, roughly 45 minutes round trip.',
    location_name: 'Corona Arch Trailhead',
    lat: 38.5808,
    lng: -109.6204,
    trail_id: 't005',
    activity_date: daysFromNow(1),
    activity_end_date: null,
    skill_level: 'intermediate',
    max_participants: 6,
    current_participants: 2,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: null,
    gear_required: ['trail runners', 'water', 'headlamp (if before sunrise)'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 24,
    created_at: daysAgo(0),
    user_display_name: 'Nora F.',
    user_avatar: 'NF',
  },
  {
    id: 'ap008',
    user_id: 'u008',
    post_type: 'lfg',
    activity_type: 'mtb',
    title: 'Whole Enchilada crew forming',
    description:
      'Putting together a group for the Whole Enchilada top-to-bottom next week. 26 miles from Burro Pass to the river. Need to be comfortable with sustained technical descending and long days in the saddle. Shuttle arranged, splitting the cost.',
    location_name: 'Whole Enchilada (Burro Pass to River)',
    lat: 38.5200,
    lng: -109.3400,
    trail_id: null,
    activity_date: daysFromNow(15),
    activity_end_date: null,
    skill_level: 'expert',
    max_participants: 6,
    current_participants: 3,
    permit_required: false,
    permit_type: null,
    permit_slots_available: null,
    cost_share: 35,
    gear_required: ['full-suspension bike', 'full-face helmet', 'knee pads', '3L water', 'trail snacks', 'spare tube'],
    contact_method: 'in_app',
    status: 'active',
    view_count: 203,
    created_at: daysAgo(2),
    user_display_name: 'Chris W.',
    user_avatar: 'CW',
  },
];
